version: '3.8'
services:
  fe-node-1:
    user: root
    image: starrocks/allin1-ubuntu:3.3.9
    container_name: fe-1
    hostname: StarRocks-01
    ports:
      - "9030:9030"
      - "6090:6090"
    command: [ "/bin/bash", "-c",
      "
      echo 'starting fe-leader node' && \
      /data/deploy/starrocks/fe/bin/start_fe.sh --host_type FQDN --daemon && \

      sleep 20 && \
      echo 'running nodes queries' && \
      mysql -h StarRocks-01 -P 9030 -u root < /data/init/init-nodes.sql >> /data/deploy/errors.txt 2>&1 || true && \

      sleep 20 && \
      echo 'running tables queries' && \
      mysql -h StarRocks-01 -P 9030 -u root < /data/init/init-tables.sql >> /data/deploy/errors.txt 2>&1 || true && \

      echo 'reading logs now' && \
      tail -f /data/deploy/starrocks/fe/log/fe.log" ]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - ./volumes/fe/fe-conf:/data/deploy/starrocks/fe/conf
      - ./init-sqls:/data/init
      - ./volumes/fe/fe-meta:/data/deploy/starrocks/fe/meta
    environment:
      - FE_TYPE=LEADER
    networks:
      - starrocks-network


  fe-node-2:
    user: root
    depends_on:
      - fe-node-1
    image: starrocks/allin1-ubuntu:3.3.9
    container_name: fe-2
    hostname: StarRocks-02
    command: [ "/bin/bash", "-c",
      "
      sleep 20s && \
      /data/deploy/starrocks/fe/bin/start_fe.sh --host_type FQDN --helper StarRocks-01:9010 --daemon && \
      sleep 5s && \
      tail -f /data/deploy/starrocks/fe/log/fe.log" ]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - ./volumes/fe-2/fe-conf:/data/deploy/starrocks/fe/conf
      - ./volumes/fe-2/fe-meta:/data/deploy/starrocks/fe/meta
    environment:
      - FE_TYPE=FOLLOWER
    networks:
      - starrocks-network


  be-node:
    user: root
    image: starrocks/allin1-ubuntu:3.3.9
    container_name: be
    hostname: StarRocks-03
    command: [ "/bin/bash", "-c",
      "
      /data/deploy/starrocks/be/bin/start_be.sh --daemon && \
      sleep 5s && \
      tail -f /data/deploy/starrocks/be/log/*" ]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - ./volumes/be/be-conf:/data/deploy/starrocks/be/conf
      - ./volumes/be/data-1:/data/deploy/starrocks/be/storage
    networks:
      - starrocks-network


  be-node-2:
    user: root
    image: starrocks/allin1-ubuntu:3.3.9
    container_name: be-2
    hostname: StarRocks-04
    command: [ "/bin/bash", "-c",
      "
    /data/deploy/starrocks/be/bin/start_be.sh --daemon && \
    sleep 5s && \
    tail -f /data/deploy/starrocks/be/log/*" ]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - ./volumes/be/be-conf:/data/deploy/starrocks/be/conf
      - ./volumes/be/data-2:/data/deploy/starrocks/be/storage
    networks:
      - starrocks-network


networks:
  starrocks-network:
    driver: bridge
