version: '3.8'
services:
  minio1:
    image: minio/minio:latest
    volumes:
      - ./minio/data1:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - minio_env
    networks:
      - minio-net
    command: server http://minio{1...4}/data --console-address ":9001"

  minio2:
    image: minio/minio:latest
    volumes:
      - ./minio/data2:/data
    ports:
      - "9002:9000"
    env_file:
      - minio_env
    networks:
      - minio-net
    command: server http://minio{1...4}/data

  minio3:
    image: minio/minio:latest
    volumes:
      - ./minio/data3:/data
    ports:
      - "9003:9000"
    env_file:
      - minio_env
    networks:
      - minio-net
    command: server http://minio{1...4}/data

  minio4:
    image: minio/minio:latest
    volumes:
      - ./minio/data4:/data
    ports:
      - "9004:9000"
    env_file:
      - minio_env
    networks:
      - minio-net
    command: server http://minio{1...4}/data

networks:
  minio-net:
    driver: bridge